/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multitexteditor;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.BadLocationException;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Gabriell
 */
public class TextBox extends javax.swing.JFrame {

    /**
     * Creates new form TextBox
     */
    
    private final String mode;
    Server servidor;
    Arquivo file;
    JTextArea TA;
    JButton CB;
    JButton S;
    JLabel FN;
    JMenuItem N;
    JMenuItem O;
    JMenuItem U;
    JMenuItem R;
    JMenuItem F;
    UndoManager manager;
    private final InputStream imgStream = TelaServidor.class.getResourceAsStream("file_txt-512.png");
    private final BufferedImage myImg;
    
    
    /** Método construtor do frame TextBox
     * @param servidor
     * @param logado
     * @param manager
     * @param TA
     * @param CB
     * @param S
     * @param FN
     * @param N
     * @param O
     * @param U
     * @param R
     * @param F
     * @param file
     * @param mode
     * @throws java.io.IOException */
    public TextBox(Server servidor, User logado, UndoManager manager, JTextArea TA, JButton CB, JButton S, JLabel FN, JMenuItem N, JMenuItem O,JMenuItem U, JMenuItem R, JMenuItem F, Arquivo file, String mode) throws IOException {
        super(mode);
        this.mode = mode;
        initComponents();
        this.myImg = ImageIO.read(imgStream);
        this.setIconImage(this.myImg);
        this.setLocationRelativeTo(null); //centraliza o frame
        this.manager = manager;
        this.setName(this.getName() + "-" + logado.getNome()); //altera o nome do frame
        this.servidor = servidor;
        this.TA = TA;
        this.CB = CB;
        this.FN = FN;
        this.S = S;
        this.N = N;
        this.O = O;
        this.U = U;
        this.R = R;
        this.F = F;
        this.file = file;
        if(!mode.equals("Encontre uma palavra")){ //significa que o frame foi chamado pela função novo ou abrir arquivo
            jRadioButtonUp.setVisible(false);
            jRadioButtonDown.setVisible(false);
        }
        else{
            //adiciona os RadioButtons ao grupo de botões
            bGroupUpDown.add(jRadioButtonUp);
            bGroupUpDown.add(jRadioButtonDown);
            jButton.setText("Localizar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /** Método que seleciona as operações a serem feitas e atualiza as condições do frame*/
    private void setFileName(){
        if(!jTextField.getText().isEmpty()){
            file.setNome(null);
            TA.setText("");
            file.setNome(jTextField.getText());
            file.setFile();
            if(mode.equals("Criar arquivo")){
                file.setTexto("");
            }else if(mode.equals("Abrir arquivo"))
                file.readFile();
            manager.discardAllEdits();
            
            file.createThread();
            servidor.startThread(file.getThread());
            
            TA.setVisible(true);
            TA.requestFocus();
            CB.setVisible(true);
            S.setVisible(true);
            FN.setText(file.getNome() + ".txt");
            FN.setVisible(true);
            N.setEnabled(false);
            O.setEnabled(false);
            R.setEnabled(true);
            U.setEnabled(true);
            F.setEnabled(true);
            this.dispose();
        }else
            JOptionPane.showMessageDialog(null, "Insira um nome"); //mensagem de erro
    }
    
    /** Método para localizar a próxima palavra que corresponde a procurada */
    private void find() throws BadLocationException{
        int chk;
        String appendedText = "", aux;
        if(!jTextField.getText().isEmpty()){
            if(jRadioButtonUp.isSelected()){
                appendedText = TA.getText(0, TA.getCaretPosition()); //associa o texto anterior ao cursor com a string
            }
            else{
                if(jRadioButtonDown.isSelected()){
                    aux = TA.getText(0, TA.getText().length()); //associa todo o texto com uma variavel auxiliar
                    appendedText = aux.substring(TA.getCaretPosition(), TA.getText().length()); //pega a substring que está depois do cursor
                }
                else
                    JOptionPane.showMessageDialog(null, "Nenhuma opção foi selecionada."); //mensagem de erro                
            }
            chk = appendedText.indexOf(jTextField.getText()); //pega o index do inicio da primeira ocorrencia da palavra procurada
            if(jRadioButtonUp.isSelected()){
                if(chk != -1)
                    TA.setCaretPosition(chk); //atualiza a posição do cursor
                else
                    JOptionPane.showMessageDialog(null, "Não há ocorrências nessa direção."); //mensagem de erro
            }
            if(jRadioButtonDown.isSelected()){
                if(chk != -1)
                    TA.setCaretPosition(chk + TA.getText().length() - appendedText.length()); //atualiza a posição do cursor
                else
                    JOptionPane.showMessageDialog(null, "Não há ocorrências nessa direção."); //mensagem de erro
            }
            this.dispose(); //fecha o frame
        }
        else{
            JOptionPane.showMessageDialog(null, "Digite um texto."); //mensagem de erro
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupUpDown = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();
        jRadioButtonUp = new javax.swing.JRadioButton();
        jRadioButtonDown = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("frameTextBox"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Insira o nome do arquivo:");

        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });
        jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKeyPressed(evt);
            }
        });

        jButton.setText("Abrir");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonKeyPressed(evt);
            }
        });

        jRadioButtonUp.setSelected(true);
        jRadioButtonUp.setText("Acima");
        jRadioButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUpActionPerformed(evt);
            }
        });

        jRadioButtonDown.setText("Abaixo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButtonUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonDown)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 141, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonUp)
                    .addComponent(jRadioButtonDown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    /** Método que determina a funcionalidade do jButton */
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:
        if(!mode.equals("Encontre uma palavra"))
            setFileName();
        else{
            try {
                find();
            } catch (BadLocationException ex) {
            }
        }
    }//GEN-LAST:event_jButtonActionPerformed

    /** Método que determina a funcionalidade do jButton */
    private void jButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonKeyPressed
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if(key == '\n'){
            if(!mode.equals("Encontre uma palavra"))
                setFileName();
            else{
                try {
                    find();
                } catch (BadLocationException ex) {
                }
            }
        }
    }//GEN-LAST:event_jButtonKeyPressed

    /** Método que determina a funcionalidade do jButton */
    private void jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyPressed
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if(key == '\n'){
            if(!mode.equals("Encontre uma palavra"))
                setFileName();
            else{
                try {
                    find();
                } catch (BadLocationException ex) {
                }
            }
        }
    }//GEN-LAST:event_jTextFieldKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jRadioButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonUpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TextBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TextBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TextBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TextBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new TextBox().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGroupUpDown;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonDown;
    private javax.swing.JRadioButton jRadioButtonUp;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
